apiVersion: v1
kind: Pod
metadata:
  name: currency-usd-app
  labels:
    app: usd-microservice
spec:
  containers:
  - name: currency-USD
    image: hashicorp/http-echo:0.2.3
    args:
      - "-text=feature available in USD"
      - -listen=:8081